use std::fs;
use std::path::{Path, PathBuf};

use semver::Version;
use serde_json::Value;
use toml_edit::{DocumentMut, value};

const MANIFESTS: [&str; 4] = [
    "package.json",
    "packages/wvst-web/package.json",
    "packages/wvst-web-examples/package.json",
    "docs/package.json",
];
const SDK_VERSION: &str = "packages/wvst-web/src/version.ts";

fn read(path: &Path) -> Result<String, String> {
    fs::read_to_string(path).map_err(|e| format!("{}: {e}", path.display()))
}
fn toml(path: &Path) -> Result<DocumentMut, String> {
    read(path)?
        .parse()
        .map_err(|e| format!("{}: {e}", path.display()))
}
fn json(path: &Path) -> Result<Value, String> {
    serde_json::from_str(&read(path)?).map_err(|e| format!("{}: {e}", path.display()))
}
fn parse_version(raw: &str) -> Result<Version, String> {
    let version = Version::parse(raw).map_err(|e| e.to_string())?;
    if !version.build.is_empty() {
        return Err("release versions must not contain build metadata".into());
    }
    Ok(version)
}
pub fn read_version(root: &Path) -> Result<Version, String> {
    let doc = toml(&root.join("Cargo.toml"))?;
    parse_version(
        doc["workspace"]["package"]["version"]
            .as_str()
            .ok_or("missing workspace.package.version")?,
    )
}
fn members(root: &Path) -> Result<Vec<(String, String)>, String> {
    let doc = toml(&root.join("Cargo.toml"))?;
    let entries = doc["workspace"]["members"]
        .as_array()
        .ok_or("missing workspace members")?;
    entries
        .iter()
        .map(|entry| {
            let path = entry.as_str().ok_or("invalid workspace member")?;
            let manifest = toml(&root.join(path).join("Cargo.toml"))?;
            if manifest["package"]["version"]["workspace"].as_bool() != Some(true) {
                return Err(format!("{path} must inherit workspace.package.version"));
            }
            let name = manifest["package"]["name"]
                .as_str()
                .ok_or("missing crate name")?;
            Ok((path.to_string(), name.to_string()))
        })
        .collect()
}
fn sdk_version(version: &Version) -> String {
    format!(
        "// Generated by wvst-release; edit workspace.package.version via release:prepare.\nexport const WVST_VERSION = \"{version}\";\n"
    )
}

pub fn check(root: &Path, tag: Option<&str>) -> Result<Version, String> {
    let version = read_version(root)?;
    if let Some(tag) = tag {
        if tag != format!("v{version}") {
            return Err(format!(
                "tag {tag} does not match workspace version v{version}"
            ));
        }
        notes(root, &version.to_string())?;
    }
    let expected = version.to_string();
    for path in MANIFESTS {
        if json(&root.join(path))?["version"].as_str() != Some(&expected) {
            return Err(format!(
                "{path} version differs from {version}; run release:sync"
            ));
        }
    }
    let lock = json(&root.join("package-lock.json"))?;
    if lock["version"].as_str() != Some(&expected) {
        return Err("npm lock root version drift".into());
    }
    for path in [
        "",
        "packages/wvst-web",
        "packages/wvst-web-examples",
        "docs",
    ] {
        if lock["packages"][path]["version"].as_str() != Some(&expected) {
            return Err(format!("npm lock workspace {path} version drift"));
        }
    }
    let cargo_lock = toml(&root.join("Cargo.lock"))?;
    let locked = cargo_lock["package"]
        .as_array_of_tables()
        .ok_or("missing Cargo lock packages")?;
    for (_, name) in members(root)? {
        let package = locked
            .iter()
            .find(|p| p["name"].as_str() == Some(&name) && !p.contains_key("source"))
            .ok_or_else(|| format!("Cargo.lock missing workspace crate {name}"))?;
        if package["version"].as_str() != Some(&expected) {
            return Err(format!("Cargo.lock {name} version drift"));
        }
    }
    // Git may check text files out with CRLF on Windows; this is not version drift.
    if read(&root.join(SDK_VERSION))?.replace("\r\n", "\n") != sdk_version(&version) {
        return Err("generated SDK version drift".into());
    }
    Ok(version)
}

struct Change {
    path: PathBuf,
    before: Option<String>,
    after: String,
}
fn change(root: &Path, path: &str, after: String) -> Result<Change, String> {
    let path = root.join(path);
    let before = if path.exists() {
        Some(read(&path)?)
    } else {
        None
    };
    Ok(Change {
        path,
        before,
        after,
    })
}
fn version_changes(root: &Path, version: &Version) -> Result<Vec<Change>, String> {
    let mut changes = Vec::new();
    let mut cargo = toml(&root.join("Cargo.toml"))?;
    cargo["workspace"]["package"]["version"] = value(version.to_string());
    changes.push(change(root, "Cargo.toml", cargo.to_string())?);
    let names: Vec<_> = members(root)?.into_iter().map(|(_, name)| name).collect();
    let mut lock = toml(&root.join("Cargo.lock"))?;
    let packages = lock["package"]
        .as_array_of_tables_mut()
        .ok_or("missing Cargo lock packages")?;
    for name in names {
        let package = packages
            .iter_mut()
            .find(|p| p["name"].as_str() == Some(&name) && !p.contains_key("source"))
            .ok_or_else(|| format!("Cargo.lock missing {name}; run cargo check first"))?;
        package["version"] = value(version.to_string());
    }
    changes.push(change(root, "Cargo.lock", lock.to_string())?);
    for path in MANIFESTS {
        let text = read(&root.join(path))?;
        let edited =
            super::json_edit::replace_versions(&text, &[vec!["version"]], &version.to_string())?;
        changes.push(change(root, path, edited)?);
    }
    let text = read(&root.join("package-lock.json"))?;
    let mut targets = vec![vec!["version"]];
    for path in [
        "",
        "packages/wvst-web",
        "packages/wvst-web-examples",
        "docs",
    ] {
        targets.push(vec!["packages", path, "version"]);
    }
    let edited = super::json_edit::replace_versions(&text, &targets, &version.to_string())?;
    changes.push(change(root, "package-lock.json", edited)?);
    changes.push(change(root, SDK_VERSION, sdk_version(version))?);
    Ok(changes)
}
fn apply(changes: Vec<Change>) -> Result<(), String> {
    for (index, change) in changes.iter().enumerate() {
        if let Err(error) = fs::write(&change.path, &change.after) {
            let mut failures = Vec::new();
            for previous in changes[..=index].iter().rev() {
                let restored = match &previous.before {
                    Some(text) => fs::write(&previous.path, text),
                    None => {
                        if previous.path.exists() {
                            fs::remove_file(&previous.path)
                        } else {
                            Ok(())
                        }
                    }
                };
                if let Err(e) = restored {
                    failures.push(format!("{}: {e}", previous.path.display()));
                }
            }
            return Err(format!(
                "write {} failed: {error}; rollback errors: {failures:?}",
                change.path.display()
            ));
        }
    }
    Ok(())
}
pub fn sync(root: &Path) -> Result<Version, String> {
    let version = read_version(root)?;
    apply(version_changes(root, &version)?)?;
    check(root, None)
}

pub fn prepare(root: &Path, raw: &str, date: &str) -> Result<Version, String> {
    check(root, None)?;
    let version = parse_version(raw)?;
    validate_date(date)?;
    let text = read(&root.join("CHANGELOG.md"))?;
    for line in text.lines().filter(|line| line.starts_with("## [")) {
        let end = line.find(']').ok_or("malformed changelog heading")?;
        let previous = &line[4..end];
        if previous != "Unreleased" && version <= parse_version(previous)? {
            return Err(format!(
                "new version {version} must be newer than changelog version {previous}"
            ));
        }
    }
    let marker = "## [Unreleased]\n";
    if text.matches(marker).count() != 1 {
        return Err("CHANGELOG.md needs exactly one Unreleased section".into());
    }
    let start = text.find(marker).ok_or("missing Unreleased section")? + marker.len();
    let end = text[start..]
        .find("\n## [")
        .map_or(text.len(), |i| start + i);
    let body = text[start..end].trim();
    if !body.lines().any(|line| line.starts_with("- ")) {
        return Err("Unreleased needs meaningful bullet entries before preparing a version".into());
    }
    let next = format!(
        "{}\n## [{version}] - {date}\n\n{body}\n{}",
        &text[..start],
        &text[end..]
    );
    let mut changes = version_changes(root, &version)?;
    changes.push(change(root, "CHANGELOG.md", next)?);
    apply(changes)?;
    check(root, Some(&format!("v{version}")))
}
fn validate_date(date: &str) -> Result<(), String> {
    let parts: Vec<_> = date.split('-').collect();
    if parts.len() != 3 || parts[0].len() != 4 || parts[1].len() != 2 || parts[2].len() != 2 {
        return Err("date must be YYYY-MM-DD".into());
    }
    let year = parts[0].parse::<u32>().map_err(|_| "invalid date")?;
    let month = parts[1].parse::<u32>().map_err(|_| "invalid date")?;
    let day = parts[2].parse::<u32>().map_err(|_| "invalid date")?;
    let leap = year % 4 == 0 && (year % 100 != 0 || year % 400 == 0);
    let max = match month {
        2 => {
            if leap {
                29
            } else {
                28
            }
        }
        4 | 6 | 9 | 11 => 30,
        1 | 3 | 5 | 7 | 8 | 10 | 12 => 31,
        _ => 0,
    };
    if year == 0 || day == 0 || day > max {
        return Err("invalid calendar date".into());
    }
    Ok(())
}
pub fn notes(root: &Path, raw: &str) -> Result<String, String> {
    parse_version(raw)?;
    let text = read(&root.join("CHANGELOG.md"))?;
    let prefix = format!("## [{raw}] - ");
    let lines: Vec<_> = text.lines().collect();
    let matching: Vec<_> = lines
        .iter()
        .enumerate()
        .filter(|(_, line)| line.starts_with(&prefix))
        .collect();
    if matching.len() != 1 {
        return Err(format!("CHANGELOG.md needs one dated section for {raw}"));
    }
    let (start, heading) = matching[0];
    validate_date(heading.strip_prefix(&prefix).ok_or("invalid heading")?)?;
    let end = lines[start + 1..]
        .iter()
        .position(|line| line.starts_with("## ["))
        .map_or(lines.len(), |i| start + 1 + i);
    let body = lines[start + 1..end].join("\n");
    if !body.lines().any(|line| line.starts_with("- ")) {
        return Err("release notes must contain bullet entries".into());
    }
    Ok(format!("{heading}\n\n{}\n", body.trim()))
}
