export const demoCopy = {
  en: {
    studioTitle: "A little studio. A real signal chain.",
    studioIntro: "Bring your native effects into the browser. Add a track, shape the sound, and hear the difference.",
    guide: "How to get connected",
    stepBridge: "Connect your Bridge",
    stepAudio: "Choose your audio",
    stepEffect: "Add an effect",
    stepBridgeHint: "Run your plugins locally",
    stepAudioHint: "A file or our synth loop",
    stepEffectHint: "Then press play",
    offline: "Bridge offline",
    browserReady: "Browser ready",
    browserBlocked: "Browser needs setup",
    offlineTitle: "Your studio starts here.",
    offlineBody: "Start the WVST Bridge on this computer to discover your VST3 effects. You can explore the player before connecting.",
    connectionHelp: "Installation & connection help",
    advanced: "Advanced connection settings",
    diagnostics: "Browser diagnostics",
    retryHint: "Bridge running? Connect to find your plugins.",
    localNote: "Audio stays on this computer.",
    guideLink: "Demo guide",
    source: "Audio source",
    sourceCaption: "A track to experiment with",
    sample: "Try a synth loop",
    sampleHint: "8 seconds · generated on your device",
    fileHint: "WAV, MP3, FLAC & more",
    uploadPrivacy: "Your file stays local",
    seek: "Playback position",
    waveformEmpty: "Your waveform will appear here",
    nowPlaying: "Playing",
    paused: "Ready to play",
    output: "Stereo output",
    outputHint: "Output level",
    sampleLoading: "Preparing audio…",
    audioError: "This audio could not be played. Try another file.",
    rackTitle: "Shape your sound.",
    rackHint: "Audio flows through your effects from top to bottom.",
    available: "available",
    rackOffline: "Your effects will meet you here.",
    rackOfflineBody: "Connect the local Bridge to browse your installed VST3 effects. In the meantime, try the player on the left.",
    rackNoPlugins: "No effects discovered yet.",
    rackNoPluginsBody: "Install a VST3 effect on this computer, then rescan. Check the demo guide if your plugin does not appear.",
    rackReady: "Your first effect is one click away.",
    rackReadyBody: "Choose an installed effect above and add it to the chain. Add more to build your own sound.",
    scanHint: "Find newly installed plugins",
    effectActive: "Processing",
    effectBypassed: "Bypassed",
    removing: "Removing…",
    technical: "Processing details",
    pluginLatency: "Plugin latency",
    parametersHint: "Adjust a parameter to hear the change.",
    signalPath: "Your signal path",
    noEffects: "No active effects",
    directAudio: "Original audio",
    processedAudio: "Effects enabled",
    listenHint: "Press play, then bypass an effect to compare.",
    supportTitle: "A few things to know.",
    helpNoSound: "I cannot hear anything",
    helpNoSoundBody: "Choose a track and press play. Check the player volume and your system output. If an effect is silent, bypass it to check the original audio.",
    helpPlugins: "Which plugins can I use?",
    helpPluginsBody: "This rack is for installed VST3 effects with stereo input and output. Instrument plugins need MIDI and are covered in the instrument example. macOS is the first supported platform.",
    helpLatency: "Why is there a short delay?",
    helpLatencyBody: "Audio travels through the local Bridge and back using a small buffer. Processing details show plugin-reported latency and buffer counters; these are not end-to-end latency measurements.",
    sessionNote: "LIVE STUDIO / LOCAL PROCESSING",
    listenOriginal: "Preview the original audio while you set up the Bridge.",
    chooseFile: 'Choose audio', dropFile: 'Drop an audio file here', replaceFile: 'Replace audio', noFile: 'No audio loaded',
    connect: 'Connect', disconnect: 'Disconnect', scan: 'Rescan', scanning: 'Scanning plugins', add: 'Mount effect',
    play: 'Play', pause: 'Pause', stop: 'Stop', back: 'Back 10 seconds', forward: 'Forward 10 seconds', loop: 'Loop',
    mute: 'Mute', unmute: 'Unmute', endpoint: 'Bridge endpoint', token: 'Session token', tokenHint: 'Match WVST_TOKEN',
    settings: 'Connection settings', prerequisites: 'Browser readiness', secureContext: 'Secure context', isolation: 'Cross-origin isolation',
    sharedBuffer: 'SharedArrayBuffer', ready: 'Ready', missing: 'Missing', selectPlugin: 'Choose an effect VST',
    emptyRack: 'The rack is empty', emptyRackBody: 'Connect the bridge, choose an effect and mount it into the signal path.',
    noPlugins: 'No effect plugins found', connecting: 'Looking for the local Bridge', connected: 'Bridge connected', blocked: 'Low-latency prerequisites are missing.',
    bridgeError: 'Bridge connection failed.', fileReady: 'Audio is ready', invalidFile: 'Choose a supported audio file.',
    mounted: 'Effect mounted', removed: 'Effect removed', meters: 'Realtime metrics', bypass: 'Bypass', enable: 'Enable',
    remove: 'Remove', up: 'Move up', down: 'Move down', status: 'Runtime status', failures: 'Scan failures', dryPath: 'Dry path',
    processedPath: 'WVST path', volume: 'Output volume', parameters: 'Plugin parameters', noParameters: 'No editable parameters reported',
    inputQueue: 'Input', outputQueue: 'Output', underflows: 'Underflow', overflows: 'Overflow', latency: 'Latency',
    bridgePanel: 'Bridge and browser status', rackPanel: 'Effect rack'
  },
  zh: {
    studioTitle: "小小工作台，真实的声音链路。",
    studioIntro: "把你的原生效果器带进浏览器。选一段音频，调整声音，听见每一次变化。",
    guide: "开始使用",
    stepBridge: "连接 Bridge",
    stepAudio: "选择音频",
    stepEffect: "添加效果器",
    stepBridgeHint: "让本地插件准备就绪",
    stepAudioHint: "自己的文件，或合成片段",
    stepEffectHint: "然后，按下播放",
    offline: "Bridge 未连接",
    browserReady: "浏览器已就绪",
    browserBlocked: "浏览器需要配置",
    offlineTitle: "你的声音实验，从这里开始。",
    offlineBody: "在这台电脑上启动 WVST Bridge，就能找到本地 VST3 效果器。连接前也可以先体验播放器。",
    connectionHelp: "安装与连接帮助",
    advanced: "高级连接设置",
    diagnostics: "浏览器诊断",
    retryHint: "Bridge 已启动？连接后即可发现插件。",
    localNote: "音频始终留在这台电脑上。",
    guideLink: "使用指南",
    source: "音频源",
    sourceCaption: "选一段声音，开始实验",
    sample: "试听合成片段",
    sampleHint: "8 秒 · 在你的设备上生成",
    fileHint: "支持 WAV、MP3、FLAC 等格式",
    uploadPrivacy: "文件只在本机读取",
    seek: "播放位置",
    waveformEmpty: "音频波形将在这里显示",
    nowPlaying: "播放中",
    paused: "准备播放",
    output: "立体声输出",
    outputHint: "输出电平",
    sampleLoading: "正在准备音频…",
    audioError: "无法播放这段音频，请尝试其他文件。",
    rackTitle: "调出你的声音。",
    rackHint: "音频从上到下，依次经过每个效果器。",
    available: "个可用",
    rackOffline: "你的效果器，将在这里就位。",
    rackOfflineBody: "连接本地 Bridge，即可浏览已安装的 VST3 效果器。也可以先试听左侧播放器。",
    rackNoPlugins: "还没有发现效果器。",
    rackNoPluginsBody: "在这台电脑上安装 VST3 效果器，再重新扫描。如果插件未出现，可以查看使用指南。",
    rackReady: "距离第一个效果器，只差一步。",
    rackReadyBody: "在上方选一个已安装的效果器，添加到信号链。还可以叠加多个效果器，探索不同声音。",
    scanHint: "查找新安装的插件",
    effectActive: "处理中",
    effectBypassed: "已旁路",
    removing: "正在移除…",
    technical: "处理详情",
    pluginLatency: "插件延迟",
    parametersHint: "调整参数，听见声音的变化。",
    signalPath: "当前信号路径",
    noEffects: "未启用效果器",
    directAudio: "原始音频",
    processedAudio: "效果器已启用",
    listenHint: "开始播放，然后旁路效果器，对比前后的声音。",
    supportTitle: "使用时，你可能想知道。",
    helpNoSound: "为什么没有声音？",
    helpNoSoundBody: "选择音频并按下播放，检查播放器音量和系统输出设备。如果加载效果器后没有声音，可以先旁路它，确认原始音频能正常播放。",
    helpPlugins: "可以使用哪些插件？",
    helpPluginsBody: "这个机架面向本机安装的 VST3 效果器，需要立体声输入和输出。音源插件需要 MIDI，请参考 instrument 示例。目前优先支持 macOS。",
    helpLatency: "为什么声音会有一点延迟？",
    helpLatencyBody: "音频通过一小段缓冲，往返于本地 Bridge。处理详情显示插件报告的延迟和缓冲计数，并不是整条链路的端到端延迟。",
    sessionNote: "声音工作台 / 本地处理",
    listenOriginal: "配置 Bridge 的同时，也可以先试听原始音频。",
    chooseFile: '选择音频', dropFile: '拖入音频文件', replaceFile: '替换音频', noFile: '尚未加载音频',
    connect: '连接', disconnect: '断开', scan: '重新扫描', scanning: '正在扫描插件', add: '挂载效果器',
    play: '播放', pause: '暂停', stop: '停止', back: '后退 10 秒', forward: '前进 10 秒', loop: '循环',
    mute: '静音', unmute: '取消静音', endpoint: 'Bridge 地址', token: 'Session Token', tokenHint: '与 WVST_TOKEN 一致',
    settings: '连接设置', prerequisites: '浏览器就绪状态', secureContext: '安全上下文', isolation: '跨域隔离',
    sharedBuffer: 'SharedArrayBuffer', ready: '就绪', missing: '缺失', selectPlugin: '选择 Effect VST',
    emptyRack: '效果器机架为空', emptyRackBody: '连接 Bridge，选择效果器并把它挂载到信号链。',
    noPlugins: '没有找到效果器插件', connecting: '正在寻找本地 Bridge', connected: 'Bridge 已连接', blocked: '缺少低延迟前置条件。',
    bridgeError: 'Bridge 连接失败。', fileReady: '音频已就绪', invalidFile: '请选择浏览器支持的音频文件。',
    mounted: '效果器已挂载', removed: '效果器已移除', meters: '实时指标', bypass: 'Bypass', enable: '启用',
    remove: '移除', up: '上移', down: '下移', status: '运行状态', failures: '扫描失败', dryPath: 'Dry Path',
    processedPath: 'WVST Path', volume: '输出音量', parameters: '插件参数', noParameters: '插件未报告可编辑参数',
    inputQueue: '输入', outputQueue: '输出', underflows: '欠载', overflows: '溢出', latency: '延迟',
    bridgePanel: 'Bridge 与浏览器状态', rackPanel: '效果器机架'
  }
};
