export {
  WVSTClient,
  type BridgeHelloResult,
  type ConnectOptions,
  type HelloParams,
  type HelloRequest,
  type LowLatencyPrerequisites,
  type MetadataInvalidationRefreshErrorListener,
  type MetadataInvalidationRefreshListener,
  type MetadataInvalidationRefreshOptions,
  type MetadataInvalidationRefreshResult,
  type MetadataInvalidationSubscriptionOptions,
  type ProtocolVersion,
} from "./client/client.js";
export {
  WebSocketRpcTransport,
  WVSTBridgeError,
  type BridgeEvent,
  type BridgeEventKind,
  type BridgeEventListener,
  type BridgeEventsOptions,
  type BridgeEventsResult,
  type BridgeMetrics,
  type WorkerRecoveryMode,
  type JsonValue,
  type RpcTransport,
  type Vst3ComponentHandlerEventKind,
  type Vst3MetadataRefreshPolicy,
  type Vst3MetadataInvalidationReason,
  type Vst3RestartFlags,
} from "./client/transport.js";
export {
  WVSTBridgeWorkerClient,
  type BridgeWorkerAudioStreamOptions,
  type BridgeWorkerClientOptions,
  type BridgeWorkerMidiEventOptions,
  type BridgeWorkerParameterEventOptions,
} from "./client/worker-client.js";
export {
  LoopbackCounter,
  configureLoopbackAudioWorkletNode,
  createLoopbackAudioWorkletNode,
  createLoopbackSharedBuffers,
  readLoopbackOutput,
  readLoopbackMetrics,
  writeLoopbackInput,
  type LoopbackBufferOptions,
  type LoopbackMetrics,
  type LoopbackNodeOptions,
  type LoopbackSharedBuffers,
} from "./audio/loopback.js";
export {
  WVST_DEFAULT_KEYBOARD_MIDI_MAP,
  createWVSTVirtualKeyboard,
  createWVSTWebMidiAdapter,
  handleWVSTVirtualKeyboardEvent,
  webMidiMessageToWVSTEvents,
  type WVSTKeyboardEventMapOptions,
  type WVSTMidiEventTarget,
  type WVSTVirtualKeyboard,
  type WVSTVirtualKeyboardNoteOptions,
  type WVSTVirtualKeyboardOptions,
  type WVSTWebMidiAccess,
  type WVSTWebMidiAdapter,
  type WVSTWebMidiAdapterOptions,
  type WVSTWebMidiInput,
  type WVSTWebMidiInputCollection,
  type WVSTWebMidiMessageEvent,
  type WVSTWebMidiRequestOptions,
} from "./midi/index.js";
export {
  type InstanceApi,
  type InstanceConnectionNotifyOptions,
  type InstanceConnectionNotifyAndRefreshOptions,
  type InstanceConnectionNotifyAndRefreshResult,
  type InstanceConnectionNotifyResult,
  type InstanceCreateOptions,
  type InstanceDescriptor,
  type InstanceDestroyOptions,
  type InstanceDestroyResult,
  type InstanceGetStateOptions,
  type InstanceGetStateResult,
  type InstanceDataPlaneSnapshot,
  type InstanceMetadataRefreshOptions,
  type InstanceMetadataRefreshResult,
  type InstanceParameterEditAggregateResult,
  type InstanceParameterEditOptions,
  type InstanceParameterGetOptions,
  type InstanceParameterGetResult,
  type InstanceParameterBeginEditOptions,
  type InstanceParameterBeginEditResult,
  type InstanceParameterEndEditOptions,
  type InstanceParameterEndEditResult,
  type InstanceParameterEditResult,
  type InstanceParameterInfoOptions,
  type InstanceParameterInfoResult,
  type InstanceParameterNormalizedByPlainOptions,
  type InstanceParameterNormalizedByPlainResult,
  type InstanceParameterPerformEditOptions,
  type InstanceParameterPerformEditResult,
  type InstanceParameterSetOptions,
  type InstanceParameterSetResult,
  type InstanceParameterValueByStringOptions,
  type InstanceParameterValueByStringResult,
  type InstanceParametersOptions,
  type InstanceParametersResult,
  type InstanceProgramDataOptions,
  type InstanceProgramDataResult,
  type InstanceProgramDataSupportedResult,
  type InstanceProcessingOptions,
  type InstanceProcessingResult,
  type InstanceRefreshRequestOptions,
  type InstanceRestartOptions,
  type InstanceRestartResult,
  type InstanceRuntimeSnapshotOptions,
  type InstanceRuntimeSnapshotResult,
  type InstanceSelectUnitOptions,
  type InstanceSelectUnitResult,
  type InstanceSetProgramDataAndRefreshOptions,
  type InstanceSetProgramDataAndRefreshResult,
  type InstanceSetProgramDataOptions,
  type InstanceSetProgramDataResult,
  type InstanceSetStateAndRefreshOptions,
  type InstanceSetStateAndRefreshResult,
  type InstanceSetStateOptions,
  type InstanceSetStateResult,
  type InstanceSetUnitDataAndRefreshOptions,
  type InstanceSetUnitDataAndRefreshResult,
  type InstanceSetUnitDataOptions,
  type InstanceSetUnitDataResult,
  type InstanceSetUnitProgramDataAndRefreshOptions,
  type InstanceSetUnitProgramDataAndRefreshResult,
  type InstanceSetUnitProgramDataOptions,
  type InstanceSetUnitProgramDataResult,
  type InstanceStatusOptions,
  type InstanceStatusResult,
  type InstanceUnitByBusOptions,
  type InstanceUnitByBusResult,
  type InstanceUnitDataOptions,
  type InstanceUnitDataResult,
  type InstanceUnitDataSupportedResult,
  type InstanceUnitsOptions,
  type InstanceUnitsResult,
  type InstanceWorkerMetrics,
  type RuntimeTailInfo,
  type SharedAudioRingCursorState,
  type SharedAudioRingLayout,
  type SharedAudioTransportConfig,
  type SharedAudioTransportLayout,
  type StreamSharedMemoryCreateOptions,
  type StreamSharedMemoryCreateResult,
  type StreamSharedMemoryDescriptor,
  type StreamSharedMemoryDestroyResult,
  type StreamSharedMemoryError,
  type StreamSharedMemoryInputEventReport,
  type StreamSharedMemoryProcessOptions,
  type StreamSharedMemoryProcessResult,
  type StreamSharedMemoryPumpConfig,
  type StreamSharedMemoryPumpClearEventsResult,
  type StreamSharedMemoryPumpEnqueueEventsOptions,
  type StreamSharedMemoryPumpEnqueueEventsResult,
  type StreamSharedMemoryPumpEventOverflowPolicy,
  type StreamSharedMemoryPumpEventQueueStatus,
  type StreamSharedMemoryPumpLastError,
  type StreamSharedMemoryPumpRingStatus,
  type StreamSharedMemoryPumpScheduleStatus,
  type StreamSharedMemoryPumpSchedulingConfig,
  type StreamSharedMemoryPumpSchedulingMode,
  type StreamSharedMemoryPumpStartOptions,
  type StreamSharedMemoryPumpStartResult,
  type StreamSharedMemoryPumpStatus,
  type StreamSharedMemoryPumpStatusResult,
  type StreamSharedMemoryPumpStopResult,
  type StreamSharedMemoryPumpTickOutcome,
  type StreamSharedMemoryRingStatus,
  type StreamSharedMemoryStatus,
  type StreamSharedMemoryStatusResult,
  type StreamSharedMemoryWorkerDetachResult,
  type StreamLifecycleOptions,
  type Vst3AudioBusDirection,
  type Vst3ConnectionPointDiagnostics,
  type Vst3MessageAttribute,
  type Vst3ParameterFlags,
  type Vst3ParameterInfo,
  type Vst3ProgramInfo,
  type Vst3ProgramList,
  type Vst3UnitInfoEntry,
  type Vst3UnitMetadata,
  type Vst3WorkerAudioBusDiagnostics,
  type Vst3WorkerAudioBusInfo,
  type Vst3WorkerAudioBusType,
  type Vst3WorkerSelectedAudioBus,
} from "./control/instances.js";
export {
  createWVSTAudioInputSource,
  createWVSTAudioDeviceWatcher,
  createWVSTMediaElementOutputRoute,
  getWVSTAudioDeviceCapabilities,
  listWVSTAudioDevices,
  requestWVSTAudioInput,
  selectWVSTAudioOutputDevice,
  setWVSTAudioContextOutputDevice,
  setWVSTMediaElementOutputDevice,
  type WVSTAudioDeviceCapabilities,
  type WVSTAudioDeviceList,
  type WVSTAudioDeviceWatcher,
  type WVSTAudioDeviceWatcherOptions,
  type WVSTAudioInputOptions,
  type WVSTAudioInputSource,
  type WVSTMediaElementOutputRoute,
  type WVSTMediaElementOutputRouteOptions,
  type WVSTOutputDeviceOptions,
} from "./session/devices.js";
export {
  type PluginApi,
  type PluginClass,
  type PluginDescriptor,
  type PluginFactoryClass,
  type PluginFactoryInfo,
  type PluginFactoryInfoOptions,
  type PluginListOptions,
  type PluginScanFailure,
  type PluginScanOptions,
  type PluginScanReport,
} from "./control/plugins.js";
export {
  createWVSTWebAudioMetricsSnapshot,
  type WVSTLatencyPercentiles,
  type WVSTWebAudioMetricsSnapshot,
  type WVSTWebAudioMetricsSnapshotOptions,
} from "./session/metrics.js";
export {
  AUDIO_FRAME_HEADER_BYTES,
  AUDIO_FRAME_MAGIC,
  AUDIO_FRAME_VERSION,
  MIDI_EVENT_BYTES,
  PARAMETER_AUTOMATION_EVENT_BYTES,
  VST3_OUTPUT_EVENT_BYTES,
  VST3_OUTPUT_EVENT_FIXED_FIELDS_BYTES,
  VST3_OUTPUT_EVENT_PAYLOAD_BYTES,
  AudioSampleFormat,
  AudioFrameFlags,
  MidiEventKind,
  Vst3OutputEventKind,
  Vst3OutputEventPayloadEncoding,
  Vst3OutputEventPayloadFlags,
  audioPayloadBytes,
  decodeAudioFrame,
  decodeAudioFrameHeader,
  decodeMidiEvent,
  decodeMidiEvents,
  decodeParameterAutomationEvent,
  decodeParameterAutomationEvents,
  decodeVst3OutputEvent,
  decodeVst3OutputEventPayloadText,
  decodeVst3OutputEvents,
  encodeAudioFrame,
  encodeAudioFrameHeader,
  encodeMidiEvent,
  encodeMidiEvents,
  encodeParameterAutomationEvent,
  encodeParameterAutomationEvents,
  encodeVst3OutputEvent,
  encodeVst3OutputEvents,
  midiEventPayloadBytes,
  parameterAutomationEventPayloadBytes,
  vst3OutputEventPayloadBytes,
  type AudioFrameHeader,
  type DecodedAudioFrame,
  type MidiEvent,
  type ParameterAutomationEvent,
  type Vst3OutputEvent,
} from "./protocol/index.js";
export {
  createWVSTAudioDeviceSession,
  type WVSTAudioDeviceSessionMetrics,
  type WVSTAudioDeviceSession,
  type WVSTAudioDeviceSessionOptions,
  type WVSTAudioGraphRebuildRequiredEvent,
  type WVSTAudioInputSwitchOptions,
  type WVSTAudioStreamAutoRestartOptions,
  type WVSTAudioStreamRestartEvent,
  type WVSTAudioStreamRestartFailureEvent,
  type WVSTAudioStreamRestartReason,
} from "./session/device-session.js";
export {
  createWVSTSharedMemoryPumpSession,
  type WVSTSharedMemoryPumpSession,
  type WVSTSharedMemoryPumpSessionOptions,
} from "./session/shared-memory-session.js";
export {
  WVST_INSTANCE_STATE_SNAPSHOT_SCHEMA_VERSION,
  checkWVSTInstanceStateSnapshotCompatibility,
  createWVSTInstanceStateSnapshot,
  instanceStateSnapshotToSetStateOptions,
  type WVSTInstanceStateSnapshotCompatibility,
  type WVSTInstanceStateSnapshot,
} from "./control/state-snapshot.js";
export {
  WVST_SHARED_AUDIO_CURSOR_BYTES,
  createWVSTSharedAudioTransportView,
  readWVSTSharedAudioCursor,
  readWVSTSharedAudioInterleaved,
  writeWVSTSharedAudioCursor,
  writeWVSTSharedAudioInterleaved,
  wvstSharedAudioReadableFrames,
  wvstSharedAudioWritableFrames,
  type WVSTSharedAudioRingRole,
  type WVSTSharedAudioRingView,
  type WVSTSharedAudioTransportView,
} from "./audio/shared-audio-transport.js";
