export {
  WVSTClient,
  type BridgeHelloResult,
  type ConnectOptions,
  type HelloParams,
  type HelloRequest,
  type LowLatencyPrerequisites,
  type ProtocolVersion,
} from "./client.js";
export {
  WebSocketRpcTransport,
  WVSTBridgeError,
  type BridgeEvent,
  type BridgeEventKind,
  type BridgeEventListener,
  type BridgeEventsOptions,
  type BridgeEventsResult,
  type BridgeMetrics,
  type JsonValue,
  type RpcTransport,
  type Vst3ComponentHandlerEventKind,
} from "./transport.js";
export {
  WVSTBridgeWorkerClient,
  type BridgeWorkerAudioStreamOptions,
  type BridgeWorkerClientOptions,
  type BridgeWorkerMidiEventOptions,
  type BridgeWorkerParameterEventOptions,
} from "./worker-client.js";
export {
  LoopbackCounter,
  configureLoopbackAudioWorkletNode,
  createLoopbackAudioWorkletNode,
  createLoopbackSharedBuffers,
  readLoopbackOutput,
  readLoopbackMetrics,
  writeLoopbackInput,
  type LoopbackBufferOptions,
  type LoopbackMetrics,
  type LoopbackNodeOptions,
  type LoopbackSharedBuffers,
} from "./loopback.js";
export {
  type InstanceApi,
  type InstanceCreateOptions,
  type InstanceDescriptor,
  type InstanceDestroyOptions,
  type InstanceDestroyResult,
  type InstanceGetStateOptions,
  type InstanceGetStateResult,
  type InstanceParameterGetOptions,
  type InstanceParameterGetResult,
  type InstanceParameterInfoOptions,
  type InstanceParameterInfoResult,
  type InstanceParameterNormalizedByPlainOptions,
  type InstanceParameterNormalizedByPlainResult,
  type InstanceParameterSetOptions,
  type InstanceParameterSetResult,
  type InstanceParameterValueByStringOptions,
  type InstanceParameterValueByStringResult,
  type InstanceParametersOptions,
  type InstanceParametersResult,
  type InstanceProgramDataOptions,
  type InstanceProgramDataResult,
  type InstanceProgramDataSupportedResult,
  type InstanceProcessingOptions,
  type InstanceProcessingResult,
  type InstanceRestartOptions,
  type InstanceRestartResult,
  type InstanceSelectUnitOptions,
  type InstanceSelectUnitResult,
  type InstanceSetProgramDataOptions,
  type InstanceSetProgramDataResult,
  type InstanceSetStateOptions,
  type InstanceSetStateResult,
  type InstanceSetUnitDataOptions,
  type InstanceSetUnitDataResult,
  type InstanceSetUnitProgramDataOptions,
  type InstanceSetUnitProgramDataResult,
  type InstanceStatusOptions,
  type InstanceStatusResult,
  type InstanceUnitByBusOptions,
  type InstanceUnitByBusResult,
  type InstanceUnitDataOptions,
  type InstanceUnitDataResult,
  type InstanceUnitDataSupportedResult,
  type InstanceUnitsOptions,
  type InstanceUnitsResult,
  type InstanceWorkerMetrics,
  type StreamLifecycleOptions,
  type Vst3AudioBusDirection,
  type Vst3ParameterFlags,
  type Vst3ParameterInfo,
  type Vst3ProgramInfo,
  type Vst3ProgramList,
  type Vst3UnitInfoEntry,
  type Vst3UnitMetadata,
} from "./instances.js";
export {
  createWVSTAudioInputSource,
  createWVSTAudioDeviceWatcher,
  createWVSTMediaElementOutputRoute,
  getWVSTAudioDeviceCapabilities,
  listWVSTAudioDevices,
  requestWVSTAudioInput,
  selectWVSTAudioOutputDevice,
  setWVSTAudioContextOutputDevice,
  setWVSTMediaElementOutputDevice,
  type WVSTAudioDeviceCapabilities,
  type WVSTAudioDeviceList,
  type WVSTAudioDeviceWatcher,
  type WVSTAudioDeviceWatcherOptions,
  type WVSTAudioInputOptions,
  type WVSTAudioInputSource,
  type WVSTMediaElementOutputRoute,
  type WVSTMediaElementOutputRouteOptions,
  type WVSTOutputDeviceOptions,
} from "./devices.js";
export {
  type PluginApi,
  type PluginClass,
  type PluginDescriptor,
  type PluginFactoryClass,
  type PluginFactoryInfo,
  type PluginFactoryInfoOptions,
  type PluginListOptions,
  type PluginScanFailure,
  type PluginScanOptions,
  type PluginScanReport,
} from "./plugins.js";
export {
  AUDIO_FRAME_HEADER_BYTES,
  AUDIO_FRAME_MAGIC,
  AUDIO_FRAME_VERSION,
  MIDI_EVENT_BYTES,
  PARAMETER_AUTOMATION_EVENT_BYTES,
  AudioSampleFormat,
  AudioFrameFlags,
  MidiEventKind,
  audioPayloadBytes,
  decodeAudioFrame,
  decodeAudioFrameHeader,
  decodeMidiEvent,
  decodeMidiEvents,
  decodeParameterAutomationEvent,
  decodeParameterAutomationEvents,
  encodeAudioFrame,
  encodeAudioFrameHeader,
  encodeMidiEvent,
  encodeMidiEvents,
  encodeParameterAutomationEvent,
  encodeParameterAutomationEvents,
  midiEventPayloadBytes,
  parameterAutomationEventPayloadBytes,
  type AudioFrameHeader,
  type DecodedAudioFrame,
  type MidiEvent,
  type ParameterAutomationEvent,
} from "./protocol.js";
export {
  createWVSTAudioDeviceSession,
  type WVSTAudioDeviceSession,
  type WVSTAudioDeviceSessionOptions,
  type WVSTAudioInputSwitchOptions,
} from "./session.js";
